FROM MacOSVenturaWithBrew AS flipperzero-toolchain-mac-build-base

RUN brew update-reset
RUN brew install gettext texinfo coreutils bison flex m4 xz || true
RUN brew link bison --force

ADD https://developer.arm.com/-/media/Files/downloads/gnu/12.3.rel1/srcrel/arm-gnu-toolchain-src-snapshot-12.3.rel1.tar.xz /toolchain/src/archives/
ADD scripts/ /toolchain/src/

RUN tar -xf /toolchain/src/archives/arm-gnu-toolchain-src-snapshot-12.3.rel1.tar.xz -C /toolchain/src/src/

RUN bash /toolchain/src/build-mac-build-libs.sh
