##
## flipperzero-toolchain-linux-binutils
##
FROM flipperzero-toolchain-linux-build-base AS flipperzero-toolchain-linux-binutils

WORKDIR /toolchain/src

RUN . /toolchain/src/buildvars.sh \
    && /toolchain/src/build-linux-binutils.sh \
    && cleanup_after_build

