name: 'Build toolchain'

on:
  push:
    branches:
      - 'asdx/**'
      - main
    tags:
      - '*'
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
   contents: read

jobs:
  build-linux:
    name: build toolchain for linux/${{ matrix.config.arch }}
    runs-on: ${{ matrix.config.runner_os }}

    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            arch: arm64,
            runner_os:  ubuntu-24.04-arm
          }
        - {
            arch: amd64,
            runner_os: ubuntu-24.04
          }

    env:
      IMAGE_NAME: flipperzero-toolchain-linux
      IMAGE_ARCH: ${{ matrix.config.arch }}

    steps:
      - name: 'checkout code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ github.event.pull_request.head.sha }}

      - name: 'Set image tag and name'
        id: tag
        run: |
          IMAGE_TAG="0"
          if [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
            REF=${{ github.ref }};
            TAG_FULL=${REF#refs/*/};
            IMAGE_TAG=${TAG_FULL//\//_};
          fi
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
  
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: merge dockerfiles
        run: |
          cat ./linux/Dockerfile.* > ./linux/Dockerfile

      - name: build and export base_build image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          file: ./linux/Dockerfile
          context: ./linux/
          tags: ${IMAGE_NAME}:${IMAGE_TAG}
          load: true
          outputs: type=docker,dest=${{ runner.temp }}/${IMAGE_NAME}_${IMAGE_TAG}_${IMAGE_ARCH}.tar
          cache-from: type=gha,scope=${IMAGE_NAME}_${IMAGE_TAG}_${IMAGE_ARCH}
          cache-to: type=gha,mode=max,scope=${IMAGE_NAME}_${IMAGE_TAG}_${IMAGE_ARCH}
