name: 'Build toolchain'

on:
  push:
    branches:
      - 'asdx/**'
      - main
    tags:
      - '*'
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
   contents: read

jobs:
  build-linux:
    name: build toolchain for linux/${{ matrix.config.arch }}
    runs-on: ${{ matrix.config.runner_os }}

    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            arch: arm64,
            runner_os:  ubuntu-24.04-arm
          }
        - {
            arch: amd64,
            runner_os: ubuntu-24.04
          }

    env:
      IMAGE_NAME: flipperzero-toolchain-linux
      IMAGE_ARCH: ${{ matrix.config.arch }}

    steps:
      - name: 'checkout code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ github.event.pull_request.head.sha }}

      - name: 'Set image tag and name'
        id: meta
        run: |
          IMAGE_TAG="0"
          if [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
            REF=${{ github.ref }};
            TAG_FULL=${REF#refs/*/};
            IMAGE_TAG=${TAG_FULL//\//_};
          fi
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
          echo "image_name=${IMAGE_NAME}" >> $GITHUB_OUTPUT
          echo "image_arch=${IMAGE_ARCH}" >> $GITHUB_OUTPUT

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: merge dockerfiles
        run: |
          cat ./linux/Dockerfile.* > ./linux/Dockerfile

      - name: check free space
        run: |
            echo "::group::/usr/local/bin/"
            du -hsc /usr/local/bin/*
            echo "::endgroup::"

            echo "::group:://usr/local/share"
            du -hsc /usr/local/share/*
            echo "::endgroup::"

            echo "::group::/usr/local/lib/"
            du -hsc /usr/local/lib/*
            echo "::endgroup::"

            echo "::group::/opt/hostedtoolcache/"
            du -hsc /opt/hostedtoolcache/*
            echo "::endgroup::"



#      - name: build and export base_build image
#        id: docker_build
#        uses: docker/build-push-action@v6
#        with:
#          file: ./linux/Dockerfile
#          context: ./linux/
#          tags: ${{ steps.meta.outputs.image_name }}:${{ steps.meta.outputs.image_tag }}
#          load: true
#          outputs: type=docker,dest=${{ runner.temp }}/${{ steps.meta.outputs.image_name }}_${{ steps.meta.outputs.image_tag }}_${{ steps.meta.outputs.image_arch }}.tar
#          cache-from: type=gha,scope=${{ steps.meta.outputs.image_name }}_${{ steps.meta.outputs.image_tag }}_${{ steps.meta.outputs.image_arch }}
#          cache-to: type=gha,mode=max,scope=${{ steps.meta.outputs.image_name }}_${{ steps.meta.outputs.image_tag }}_${{ steps.meta.outputs.image_arch }}
