name: 'Build toolchain'

on:
  push:
    branches:
      - 'asdx/**'
      - main
    tags:
      - '*'
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
   contents: read

jobs:

  linux-arm64-build-base:
    name: build base image for linux/arm64
    runs-on: ubuntu-24.04-arm

    steps:
      - name: 'checkout code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ github.event.pull_request.head.sha }}

      - name: 'generate metadata'
        id: meta
        env:
          IMAGE_NAME: flipperzero-toolchain-linux-build-base
        run: |
            IMAGE_TAG="${IMAGE_NAME}"
            echo "tags=${IMAGE_TAG}" >> "$GITHUB_OUTPUT"

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: build base_build container
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          file: ./linux/Dockerfile.step1.build-base
          context: ./linux/
          load: true
          tags: ${{ steps.meta.output.tags }}
          cache-from: type=gha,scope=flipperzero-toolchain-linux-arm64-cache
          cache-to: type=gha,mode=max,scope=flipperzero-toolchain-linux-arm64-cache

  linux-arm64-build-components:
    name: build ${{ matrix.component }}
    needs: [linux-arm64-build-base]
    runs-on: ubuntu-24.04-arm

    strategy:
      fail-fast: false
      matrix:
        component:
          - binutils
          - gcc
          - llvm
          - python-with-gdb
          - tools

    steps:
      - name: 'checkout code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ github.event.pull_request.head.sha }}

      - name: 'generate metadata'
        id: meta
        run: |
            echo "tags=flipperzero-toolchain-linux-${{ matrix.component }}" >> "$GITHUB_OUTPUT"

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: build base_build container
        uses: docker/build-push-action@v6
        with:
          file: ./linux/Dockerfile.step2.${{ matrix.component }}
          context: ./linux/
          load: true
          tags: ${{ steps.meta.output.tags }}
          cache-from: type=gha,scope=flipperzero-toolchain-linux-arm64-cache
          cache-to: type=gha,mode=max,scope=flipperzero-toolchain-linux-arm64-cache
  
  linux-arm64-final:
    name: build final image for linux/arm64
    needs: [linux-arm64-build-base, linux-arm64-build-components]
    runs-on: ubuntu-24.04-arm

    steps:
      - name: 'checkout code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ github.event.pull_request.head.sha }}

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: build base_build container
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          file: ./linux/Dockerfile.step3.final
          context: ./linux/
          load: true
          tags: flipperzero-toolchain-linux
          cache-from: type=gha,scope=flipperzero-toolchain-linux-arm64-cache
          cache-to: type=gha,mode=max,scope=flipperzero-toolchain-linux-arm64-cache
