name: 'Build toolchain'

on:
  push:
    branches:
      - 'asdx/**'
      - main
    tags:
      - '*'
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
   contents: read

jobs:

  linux-arm64-build-base:
    name: build base image for linux/arm64
    runs-on: ubuntu-24.04-arm

    steps:
      - name: 'checkout code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ github.event.pull_request.head.sha }}

      - name: 'generate metadata'
        id: meta
        env:
          IMAGE_NAME: flipperzero-toolchain-linux-build-base
        run: |
            IMAGE_TAG="${IMAGE_NAME}"
            echo "tags=${IMAGE_TAG}" >> "$GITHUB_OUTPUT"

      - name: build and export base_build image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          file: ./linux/Dockerfile.step1.build-base
          context: ./linux/
          tags: flipperzero-toolchain-linux-build-base:latest
          outputs: type=docker,dest=${{ runner.temp }}/flipperzero-toolchain-linux-build-base_latest.tar
          cache-from: type=gha,scope=flipperzero-toolchain-linux-arm64-cache
          cache-to: type=gha,mode=max,scope=flipperzero-toolchain-linux-arm64-cache

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flipperzero-toolchain-linux-build-base_latest
          path: ${{ runner.temp }}/flipperzero-toolchain-linux-build-base_latest.tar

  linux-arm64-build-components:
    name: build ${{ matrix.component }}
    needs: [linux-arm64-build-base]
    runs-on: ubuntu-24.04-arm

    strategy:
      fail-fast: false
      matrix:
        component:
          - binutils
          - gcc
          - llvm
          - python-with-gdb
          - tools

    steps:
      - name: 'checkout code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ github.event.pull_request.head.sha }}

      - name: 'generate metadata'
        id: meta
        run: |
            echo "tags=flipperzero-toolchain-linux-${{ matrix.component }}" >> "$GITHUB_OUTPUT"

      - name: download artifacts
        uses: actions/download-artifact@v4
        with: 
          name: flipperzero-toolchain-linux-build-base_latest
          path: ${{ runner.temp }}

      - name: load image
        run: | 
          docker load --input ${{ runner.temp }}/flipperzero-toolchain-linux-build-base_latest.tar

      - name: build ${{ matrix.component }} container
        uses: docker/build-push-action@v6
        with:
          file: ./linux/Dockerfile.step2.${{ matrix.component }}
          context: ./linux/
          load: true
          tags: flipperzero-toolchain-linux-${{ matrix.component }}
          outputs: type=docker,dest=${{ runner.temp }}/flipperzero-toolchain-linux-${{ matrix.component }}_latest.tar
          cache-from: type=gha,scope=flipperzero-toolchain-linux-arm64-cache
          cache-to: type=gha,mode=max,scope=flipperzero-toolchain-linux-arm64-cache

      - name: uplaod artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flipperzero-toolchain-linux-${{ matrix.component }}_latest
          path: ${{ runner.temp }}/flipperzero-toolchain-linux-${{ matrix.component }}_latest.tar
  
  
  linux-arm64-final:
    name: build final image for linux/arm64
    needs: [linux-arm64-build-base, linux-arm64-build-components]
    runs-on: ubuntu-24.04-arm

    steps:
      - name: 'checkout code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ github.event.pull_request.head.sha }}


      - name: download artifacts
        uses: actions/download-artifact@v4
        with: 
          pattern: flipperzero-toolchain-linux-*_latest
          path: ${{ runner.temp }}
          merge-multiple: true 

      - name: load image
        run: | 
          docker load --input ${{ runner.temp }}/flipperzero-toolchain-linux-binutils_latest.tar
          docker load --input ${{ runner.temp }}/flipperzero-toolchain-linux-gcc_latest.tar
          docker load --input ${{ runner.temp }}/flipperzero-toolchain-linux-llvm_latest.tar
          docker load --input ${{ runner.temp }}/flipperzero-toolchain-linux-python-with-gdb_latest.tar
          docker load --input ${{ runner.temp }}/flipperzero-toolchain-linux-tools_latest.tar
      
      - name: build base_build container
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          file: ./linux/Dockerfile.step3.final
          context: ./linux/
          load: true
          tags: flipperzero-toolchain-linux
          cache-from: type=gha,scope=flipperzero-toolchain-linux-arm64-cache
          cache-to: type=gha,mode=max,scope=flipperzero-toolchain-linux-arm64-cache
